export interface Tool {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  href: string;
  icon: string;
  category: 'formatter' | 'encoder' | 'generator' | 'converter' | 'cheatsheet';
  keywords: string[];
}

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON 포매터',
    nameEn: 'JSON Formatter',
    description: 'JSON 데이터를 보기 좋게 정리하고 유효성을 검증합니다.',
    href: '/json-formatter',
    icon: '{ }',
    category: 'formatter',
    keywords: ['json', '포매터', 'formatter', '정리', '검증', 'validator', '뷰어'],
  },
  {
    id: 'base64',
    name: 'Base64 인코더/디코더',
    nameEn: 'Base64 Encoder/Decoder',
    description: 'Base64 문자열을 인코딩하거나 디코딩합니다.',
    href: '/base64',
    icon: 'B64',
    category: 'encoder',
    keywords: ['base64', '인코딩', '디코딩', 'encode', 'decode'],
  },
  {
    id: 'url-encoder',
    name: 'URL 인코더/디코더',
    nameEn: 'URL Encoder/Decoder',
    description: 'URL 문자열을 인코딩하거나 디코딩합니다.',
    href: '/url-encoder',
    icon: '%20',
    category: 'encoder',
    keywords: ['url', '인코딩', '디코딩', 'encode', 'decode', 'percent'],
  },
  {
    id: 'regex-tester',
    name: '정규식 테스터',
    nameEn: 'Regex Tester',
    description: '정규표현식을 실시간으로 테스트하고 매칭 결과를 확인합니다.',
    href: '/regex-tester',
    icon: '.*',
    category: 'formatter',
    keywords: ['정규식', 'regex', '정규표현식', 'regular expression', '테스트'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT 디코더',
    nameEn: 'JWT Decoder',
    description: 'JWT 토큰의 Header, Payload를 디코딩하여 확인합니다.',
    href: '/jwt-decoder',
    icon: 'JWT',
    category: 'encoder',
    keywords: ['jwt', '토큰', 'token', 'decoder', '디코더', 'json web token'],
  },
  {
    id: 'timestamp',
    name: 'Unix 타임스탬프 변환기',
    nameEn: 'Unix Timestamp Converter',
    description: 'Unix 타임스탬프와 사람이 읽을 수 있는 날짜를 상호 변환합니다.',
    href: '/timestamp',
    icon: '⏱',
    category: 'converter',
    keywords: ['unix', '타임스탬프', 'timestamp', '시간', '변환', 'epoch'],
  },
  {
    id: 'id-generator',
    name: 'UUID/ULID 생성기',
    nameEn: 'UUID/ULID Generator',
    description: 'UUID v4, ULID, NanoID를 생성합니다. 벌크 생성도 지원합니다.',
    href: '/id-generator',
    icon: '#id',
    category: 'generator',
    keywords: ['uuid', 'ulid', 'nanoid', '생성기', 'generator', '고유 식별자', 'id'],
  },
  {
    id: 'hash-generator',
    name: '해시 생성기',
    nameEn: 'Hash Generator',
    description: 'MD5, SHA-1, SHA-256 등 다양한 해시를 생성합니다.',
    href: '/hash-generator',
    icon: '#!',
    category: 'generator',
    keywords: ['hash', '해시', 'md5', 'sha256', 'sha1', '체크섬', 'checksum'],
  },
  {
    id: 'diff-checker',
    name: 'Diff 비교기',
    nameEn: 'Diff Checker',
    description: '두 텍스트의 차이점을 비교하여 시각적으로 보여줍니다.',
    href: '/diff-checker',
    icon: '±',
    category: 'formatter',
    keywords: ['diff', '비교', '차이', 'compare', '텍스트 비교'],
  },
  {
    id: 'color-converter',
    name: 'Color 변환기',
    nameEn: 'Color Converter',
    description: 'HEX, RGB, HSL 색상 값을 상호 변환합니다.',
    href: '/color-converter',
    icon: '🎨',
    category: 'converter',
    keywords: ['color', '색상', 'hex', 'rgb', 'hsl', '변환', '컬러'],
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 미리보기',
    nameEn: 'Markdown Preview',
    description: 'Markdown 문법을 실시간으로 미리보기합니다.',
    href: '/markdown-preview',
    icon: 'M↓',
    category: 'formatter',
    keywords: ['markdown', '마크다운', '미리보기', 'preview', 'md', 'README'],
  },
  {
    id: 'qr-generator',
    name: 'QR코드 생성기',
    nameEn: 'QR Code Generator',
    description: '텍스트나 URL로 QR코드를 즉시 생성합니다.',
    href: '/qr-generator',
    icon: 'QR',
    category: 'generator',
    keywords: ['qr', 'qr코드', '큐알', '생성기', 'qrcode', 'barcode'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL 포매터',
    nameEn: 'SQL Formatter',
    description: 'SQL 쿼리를 보기 좋게 정리합니다.',
    href: '/sql-formatter',
    icon: 'SQL',
    category: 'formatter',
    keywords: ['sql', '포매터', 'formatter', '쿼리', 'query', '정리'],
  },
  {
    id: 'git-cheatsheet',
    name: 'Git 명령어 모음',
    nameEn: 'Git Cheatsheet',
    description: 'Git 명령어를 카테고리별로 정리한 치트시트입니다.',
    href: '/git-cheatsheet',
    icon: 'Git',
    category: 'cheatsheet',
    keywords: ['git', '명령어', 'git rebase', 'git merge', 'git branch', 'commit', '깃'],
  },
  {
    id: 'docker-cheatsheet',
    name: 'Docker 명령어 모음',
    nameEn: 'Docker Cheatsheet',
    description: 'Docker 및 Docker Compose 명령어를 정리한 치트시트입니다.',
    href: '/docker-cheatsheet',
    icon: '🐳',
    category: 'cheatsheet',
    keywords: ['docker', '도커', 'docker compose', '컨테이너', 'container', '명령어'],
  },
  {
    id: 'http-status',
    name: 'HTTP 상태코드 정리',
    nameEn: 'HTTP Status Codes',
    description: 'HTTP 상태코드를 카테고리별로 정리하고 설명합니다.',
    href: '/http-status',
    icon: '200',
    category: 'cheatsheet',
    keywords: ['http', '상태코드', 'status code', '404', '500', '200', '301'],
  },
  {
    id: 'cron-cheatsheet',
    name: 'Cron 표현식 가이드',
    nameEn: 'Cron Expression Guide',
    description: 'Cron 표현식 문법과 주요 예제를 정리한 가이드입니다.',
    href: '/cron-cheatsheet',
    icon: '⏰',
    category: 'cheatsheet',
    keywords: ['cron', '크론탭', 'crontab', '스케줄', 'schedule', '매일 실행', '표현식'],
  },
  {
    id: 'linux-cheatsheet',
    name: 'Linux 명령어 모음',
    nameEn: 'Linux Cheatsheet',
    description: 'Linux 필수 명령어를 카테고리별로 정리한 치트시트입니다.',
    href: '/linux-cheatsheet',
    icon: '🐧',
    category: 'cheatsheet',
    keywords: ['linux', '리눅스', '명령어', 'chmod', 'grep', 'find', 'bash', '터미널'],
  },
  {
    id: 'regex-cheatsheet',
    name: '정규식 문법 정리',
    nameEn: 'Regex Cheatsheet',
    description: '정규표현식 문법과 주요 패턴을 정리한 치트시트입니다.',
    href: '/regex-cheatsheet',
    icon: '/.*/',
    category: 'cheatsheet',
    keywords: ['정규식', 'regex', '정규표현식', '패턴', '이메일', '숫자만', 'regexp'],
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML 변환기',
    nameEn: 'JSON YAML Converter',
    description: 'JSON과 YAML 형식을 양방향으로 변환합니다.',
    href: '/json-yaml',
    icon: 'Y{}',
    category: 'converter',
    keywords: ['json', 'yaml', 'yml', '변환', 'converter', '설정 파일', 'config'],
  },
  {
    id: 'text-case',
    name: 'Text Case 변환기',
    nameEn: 'Text Case Converter',
    description: '텍스트를 camelCase, snake_case, kebab-case 등 다양한 케이스로 변환합니다.',
    href: '/text-case',
    icon: 'Aa',
    category: 'converter',
    keywords: ['camelCase', 'snake_case', 'kebab-case', 'PascalCase', '케이스 변환', 'text case'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum 생성기',
    nameEn: 'Lorem Ipsum Generator',
    description: '더미 텍스트(Lorem Ipsum)를 문단, 문장, 단어 단위로 생성합니다.',
    href: '/lorem-ipsum',
    icon: 'Li',
    category: 'generator',
    keywords: ['lorem ipsum', '더미 텍스트', 'placeholder', '텍스트 생성', 'dummy text'],
  },
  {
    id: 'cron-builder',
    name: 'Cron 표현식 빌더',
    nameEn: 'Cron Expression Builder',
    description: 'GUI로 Cron 표현식을 생성하고 다음 실행 시간을 확인합니다.',
    href: '/cron-builder',
    icon: '⏲',
    category: 'generator',
    keywords: ['cron', '크론', '스케줄', 'schedule', '크론탭', 'crontab', '빌더'],
  },
];

export const categories = {
  formatter: { name: '포매터 & 검증', color: 'brand' },
  encoder: { name: '인코딩 & 디코딩', color: 'emerald' },
  generator: { name: '생성기', color: 'violet' },
  converter: { name: '변환기', color: 'amber' },
  cheatsheet: { name: '치트시트', color: 'rose' },
};
